version: '3.7'

services:
    elasticsearch:
        image: elasticsearch:7.4.0
        restart: unless-stopped
        environment:
            discovery.type: single-node
        ports:
            - 9200:9200
            - 9300:9300
    kibana:
        image: docker.elastic.co/kibana/kibana:7.4.0
        restart: unless-stopped
        depends_on:
            - elasticsearch
        ports:
            - 5601:5601